[tool.semantic_release]

branch = "main"
version_variable = "README.rst:Version,docs/conf.py:__version__,tag_fields/__init__.py:__version__"

build_command = ""
remove_dist = false
upload_to_release = false

major_on_zero = false
upload_to_pypi = false
check_build_status = false

commit_subject = ":memo: build(version): Bump to version - {version}."


[tool.bandit]
exclude_dirs = ["tests",]
# tests = ["B201", "B301"]
# skips = ["B101", "B601"]
