name: Release

on:
  # push:
  #   tags:
  #   - '*'
  workflow_dispatch:


jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the whole repository history is present, so that
          # python-semantic-release can decide if a new release is needed.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build package
        run: |
          python3 setup.py --version
          python3 setup.py sdist --format=gztar bdist_wheel
          twine check dist/*

      - uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.PYPI_RELEASE_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_RELEASE_KEY }}
