name: Release

on:
  # push:
  #   tags:
  #   - '*'
  workflow_dispatch:

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the whole repository history is present, so that
          # python-semantic-release can decide if a new release is needed.
          fetch-depth: 0

      - uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.PYPI_RELEASE_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_RELEASE_KEY }}
